/**
 * Admin Token Generation Endpoint
 * POST /api/v1/admin/generate-token
 * Generates service tokens for developers (Admin only)
 */

import { NextResponse } from 'next/server';
import crypto from 'crypto';
import { currentUser } from '@clerk/nextjs/server';
import { isAdmin } from '@/config/team-members';
import { createSuccessResponse, createErrorResponse } from '@/lib/api/errorHandler';

/**
 * POST /api/v1/admin/generate-token
 * Generate a new service token
 *
 * Request Body:
 *   {
 *     serviceId: string (unique identifier, e.g., 'dev-john-doe')
 *     name: string (developer name)
 *     email: string (developer email)
 *     tier: 'WEB_APP' | 'BATCH_JOB' | 'DEV_TESTING'
 *   }
 *
 * Response:
 *   {
 *     success: true,
 *     data: {
 *       serviceId: string,
 *       name: string,
 *       email: string,
 *       tier: string,
 *       token: string (256-bit hex),
 *       envVar: string (e.g., 'SERVICE_TOKEN_DEV_JOHN_DOE'),
 *       createdAt: ISO8601,
 *       createdBy: string
 *     }
 *   }
 */
export async function POST(request) {
  try {
    // Check authentication
    const user = await currentUser();

    if (!user) {
      return createErrorResponse({
        code: 'UNAUTHORIZED',
        message: 'Authentication required',
        status: 401
      });
    }

    const userEmail = user.emailAddresses?.[0]?.emailAddress;

    // Check admin access
    if (!isAdmin(userEmail)) {
      return createErrorResponse({
        code: 'FORBIDDEN',
        message: 'Admin access required',
        status: 403
      });
    }

    // Parse request body
    const body = await request.json();
    const { serviceId, name, email, tier } = body;

    // Validate required fields
    if (!serviceId || !name || !email || !tier) {
      return createErrorResponse({
        code: 'VALIDATION_ERROR',
        message: 'Missing required fields: serviceId, name, email, tier',
        status: 400
      });
    }

    // Validate serviceId format (lowercase, hyphens, no spaces)
    if (!/^[a-z0-9-]+$/.test(serviceId)) {
      return createErrorResponse({
        code: 'VALIDATION_ERROR',
        message: 'Service ID must be lowercase with hyphens only (e.g., dev-john-doe)',
        status: 400
      });
    }

    // Validate tier
    const validTiers = ['WEB_APP', 'BATCH_JOB', 'DEV_TESTING'];
    if (!validTiers.includes(tier)) {
      return createErrorResponse({
        code: 'VALIDATION_ERROR',
        message: `Invalid tier. Must be one of: ${validTiers.join(', ')}`,
        status: 400
      });
    }

    // Generate 256-bit token
    const token = crypto.randomBytes(32).toString('hex');

    // Generate environment variable name
    const envVar = `SERVICE_TOKEN_${serviceId.toUpperCase().replace(/-/g, '_')}`;

    // Prepare response
    const tokenData = {
      serviceId,
      name,
      email,
      tier,
      token,
      envVar,
      createdAt: new Date().toISOString(),
      createdBy: userEmail
    };

    // Log for audit trail
    console.log(`[ADMIN] Token generated by ${userEmail} for ${serviceId} (${email})`);

    return createSuccessResponse(tokenData, {
      generated: true,
      note: 'Save this token securely. It will not be shown again.'
    });

  } catch (error) {
    console.error('Token generation error:', error);
    return createErrorResponse({
      code: 'INTERNAL_ERROR',
      message: 'Failed to generate token',
      status: 500
    });
  }
}
