import { NextResponse } from 'next/server';

/**
 * POST /api/email/send-report
 *
 * Sends assessment report via email
 *
 * Note: This is a placeholder implementation. In production, you would
 * integrate with an email service like:
 * - Resend (recommended)
 * - SendGrid
 * - AWS SES
 * - Postmark
 */

export async function POST(request) {
	try {
		const body = await request.json();
		const {
			recipients,
			assessmentId,
			includeDetails,
			includePdf,
			buildingName,
			score
		} = body;

		// Validate recipients
		if (!recipients || recipients.length === 0) {
			return NextResponse.json(
				{ error: 'At least one recipient email is required' },
				{ status: 400 }
			);
		}

		// Validate email format
		const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
		const validRecipients = recipients.filter(email => emailRegex.test(email));

		if (validRecipients.length === 0) {
			return NextResponse.json(
				{ error: 'No valid email addresses provided' },
				{ status: 400 }
			);
		}

		// Get the base URL for the report link
		const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://quakewise.com';
		const reportUrl = `${baseUrl}/result/${assessmentId}`;

		// Build email content
		const emailSubject = buildingName
			? `Earthquake Safety Report: ${buildingName}`
			: 'Your Earthquake Safety Assessment Report';

		const safetyStatus = score >= 70 ? 'Safe' : score >= 50 ? 'Needs Attention' : 'At Risk';
		const scoreColor = score >= 70 ? '#10B981' : score >= 50 ? '#F59E0B' : '#EF4444';

		const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QuakeWise Safety Report</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f3f4f6;">
  <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
    <!-- Header -->
    <div style="text-align: center; margin-bottom: 30px;">
      <h1 style="color: #7C3AED; margin: 0; font-size: 28px;">QuakeWise</h1>
      <p style="color: #6B7280; margin: 5px 0 0 0;">Earthquake Safety Assessment</p>
    </div>

    <!-- Main Card -->
    <div style="background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
      <!-- Score Section -->
      <div style="padding: 40px; text-align: center; background: linear-gradient(135deg, #7C3AED20, #9333EA20);">
        <div style="width: 120px; height: 120px; border-radius: 60px; background: ${scoreColor}20; border: 4px solid ${scoreColor}; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center;">
          <span style="font-size: 42px; font-weight: bold; color: ${scoreColor};">${Math.round(score || 0)}</span>
        </div>
        <h2 style="margin: 0; color: #1F2937; font-size: 24px;">${buildingName || 'Your Building'}</h2>
        <p style="margin: 10px 0 0 0; color: ${scoreColor}; font-weight: bold; font-size: 18px;">
          ${safetyStatus}
        </p>
      </div>

      <!-- Content -->
      <div style="padding: 30px;">
        ${includeDetails ? `
        <div style="margin-bottom: 25px;">
          <h3 style="margin: 0 0 15px 0; color: #374151; font-size: 16px;">Assessment Summary</h3>
          <ul style="margin: 0; padding: 0 0 0 20px; color: #6B7280;">
            <li style="margin-bottom: 8px;">Safety Score: ${Math.round(score || 0)}/100</li>
            <li style="margin-bottom: 8px;">Status: ${safetyStatus}</li>
            <li>Assessment ID: ${assessmentId}</li>
          </ul>
        </div>
        ` : ''}

        <div style="text-align: center; margin-top: 30px;">
          <a href="${reportUrl}" style="display: inline-block; background: linear-gradient(135deg, #7C3AED, #9333EA); color: white; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">
            View Full Report
          </a>
        </div>

        ${includePdf ? `
        <p style="text-align: center; margin-top: 20px; color: #6B7280; font-size: 14px;">
          You can download the PDF report from the link above.
        </p>
        ` : ''}
      </div>
    </div>

    <!-- Footer -->
    <div style="text-align: center; margin-top: 30px; color: #9CA3AF; font-size: 12px;">
      <p>This report was generated by QuakeWise</p>
      <p>quakewise.com | AI-Powered Earthquake Safety Assessment</p>
      <p style="margin-top: 15px;">
        This assessment is based on the information provided and serves as a general guide.
        For comprehensive structural analysis, consult a licensed professional engineer.
      </p>
    </div>
  </div>
</body>
</html>
`;

		// In production, integrate with email service here
		// Example with Resend:
		// const resend = new Resend(process.env.RESEND_API_KEY);
		// await resend.emails.send({
		//   from: 'QuakeWise <reports@quakewise.com>',
		//   to: validRecipients,
		//   subject: emailSubject,
		//   html: emailHtml,
		// });

		// For now, log the email (development mode)
		console.log('Email would be sent:', {
			to: validRecipients,
			subject: emailSubject,
			reportUrl,
			score,
			includeDetails,
			includePdf
		});

		// Simulate email sending delay
		await new Promise(resolve => setTimeout(resolve, 1000));

		return NextResponse.json({
			success: true,
			message: 'Email sent successfully',
			recipients: validRecipients.length
		});

	} catch (error) {
		console.error('Email send error:', error);
		return NextResponse.json(
			{ error: 'Failed to send email', details: error.message },
			{ status: 500 }
		);
	}
}
